apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      initContainers:
        - name: output-1
          image: ${ECR_HOST}
          command:
            [
              "/bin/bash",
              "-c",
              "bundle exec rails s -p '3000' -b '0.0.0.0' -e production",
              "RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:migrate:reset",
            ]
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: rails_master_key
                  name: credentials-config
        - name: output-2
          image: ${ECR_HOST}
          command:
            [
              "/bin/bash",
              "-c",
              "bundle exec rails s -p '3000' -b '0.0.0.0' -e production",
              "RAILS_ENV=production bundle exec rails db:seed",
            ]
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: rails_master_key
                  name: credentials-config
      containers:
        - name: backend-app
          image: ${ECR_HOST}
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            ["-c", "bundle exec rails s -p '3000' -b '0.0.0.0' -e production"]
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: db-url
                  name: db-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-username
                  name: db-config
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: db-config
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: rails_master_key
                  name: credentials-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 768Mi
